package com.pavlov.MyShadowGallery.util

//object NameUtil {
//    val adjectives = listOf(
//        "Могучий",
//        "Неудержимый",
//        "Бесстрашный",
//        "Героический",
//        "Безупречный",
//        "Непоколебимый",
//        "Неуязвимый",
//        "Подвижный",
//        "Безжалостный",
//        "Несокрушимый",
//        "Несгибаемый",
//        "Невозмутимый",
//        "Непокорный",
//        "Разъяренный",
//        "Сильный",
//        "Надежный",
//        "Благородный",
//        "Смелый",
//        "Отважный",
//        "Стойкий",
//        "Бессмертный",
//        "Ловкий",
//        "Удивительный",
//        "Исступленный",
//        "Храбрый",
//        "Траурный",
//        "Забывчивый",
//        "Юный",
//        "Возросший",
//        "Активный",
//        "Неспящий",
//        "Мягкий",
//        "Ультра",
//        "Грубый"
//    )
//
//    val nouns = listOf(
//        "Герой",
//        "Воин",
//        "Защитник",
//        "Титан",
//        "Мститель",
//        "Страж",
//        "Чемпион",
//        "Драконоборец",
//        "Небожитель",
//        "Каратель",
//        "Избавитель",
//        "Молот",
//        "Меч",
//        "Заклинатель",
//        "Рыцарь",
//        "Захватчик",
//        "Разоритель",
//        "Легенда",
//        "Паладин",
//        "Юстициар",
//        "Патриций",
//        "Темплар",
//        "Надзиратель",
//        "Блюститель",
//        "Ревнитель",
//        "Кинжал",
//        "Бард",
//        "Следопыт"
//    )
//}

object NameUtil {
    val adjectives = listOf(
        "Mighty",
        "Unstoppable",
        "Fearless",
        "Heroic",
        "Flawless",
        "Unshakable",
        "Invulnerable",
        "Agile",
        "Merciless",
        "Indomitable",
        "Unbending",
        "Imperturbable",
        "Unyielding",
        "Unconquerable",
        "Strong",
        "Reliable",
        "Noble",
        "Brave",
        "Daring",
        "Steadfast",
        "Immortal",
        "Agile",
        "Amazing",
        "Furious",
        "Courageous",
        "Mournful",
        "Forgetful",
        "Young",
        "Grown",
        "Active",
        "Sleepless",
        "Soft",
        "Ultra",
        "Rough"
    )

    val nouns = listOf(
        "Hero",
        "Warrior",
        "Defender",
        "Titan",
        "Avenger",
        "Guardian",
        "Champion",
        "DragonSlayer",
        "Skyward",
        "Punisher",
        "Deliverer",
        "Hammer",
        "Sword",
        "Spellbinder",
        "Knight",
        "Invader",
        "Ravager",
        "Legend",
        "Paladin",
        "Justiciar",
        "Patrician",
        "Templar",
        "Overseer",
        "Warden",
        "Zealot",
        "Dagger",
        "Bard",
        "Tracker"
    )
}