package com.pavlov.MyShadowGallery.file

import com.pavlov.MyShadowGallery.TrackData

class ArtistNaming {
    companion object {
        val artistName = listOf(
            "The Beatles", "Rolling Stones", "Led Zeppelin", "Pink Floyd",
            "Queen", "The Who", "U2", "Nirvana", "Metallica", "AC/DC",
            "Radiohead", "Coldplay", "Red Hot Chili Peppers", "Foo Fighters",
            "The Doors", "Guns N' Roses", "The Eagles", "Bee Gees", "Fleetwood Mac",
            "Aerosmith", "Black Sabbath", "The Beach Boys", "The Police", "The Clash",
            "Pearl Jam", "Dire Straits", "R.E.M.", "Linkin Park", "Genesis",
            "Oasis", "The Cure", "Ramones", "Van Halen", "Deep Purple",
            "Bon Jovi", "Rush", "Def Leppard", "The Smiths", "ZZ Top",
            "The Kinks", "Eagles", "Creedence Clearwater Revival", "The Smashing Pumpkins", "The Supremes",
            "The Temptations", "The Four Seasons", "The Jackson 5", "The Byrds", "The Bee Gees",
            "The Carpenters", "The Mamas & the Papas", "The Everly Brothers", "The Platters", "The Isley Brothers",
            "The Drifters", "The Four Tops", "The Animals", "The Yardbirds", "The Small Faces",
            "The Hollies", "The Turtles", "The Monkees", "The Zombies", "The Searchers",
            "The Shadows", "The Ventures", "The Dave Clark Five", "The Ronettes", "The Shirelles",
            "The Chiffons", "The Crystals", "The Marvelettes", "The Vandellas", "The Miracles",
            "The Shangri-Las", "The Angels", "The Dixie Cups", "The Exciters", "The Cookies",
            "The Blossoms", "The O'Jays", "The Spinners", "The Stylistics", "The Chi-Lites",
            "The Temptations", "The Impressions", "The Delfonics", "The Dramatics", "The Four Tops",
            "The Miracles", "The Isley Brothers", "The Commodores", "The O'Jays", "The Temptations",
// Русские музыкальные коллективы
            "Ария", "Аквариум", "Сплин", "ДДТ", "Кино", "Мумий Тролль",
            "Ленинград", "Би-2", "Земфира", "Серебро", "МакSим",
            "Любэ", "Машина Времени", "Смысловые Галлюцинации", "Тату",
            "Сектор Газа", "Бутусов", "Браво", "Сплин", "МГК",
            "Танцы Минус", "Чайф", "Машина времени", "КняZz", "Смысловые Галлюцинации", "Валерий Леонтьев", "Мельница", "Канцлер ГИ", "Проще сложного",
// Испанские музыкальные коллективы
            "Maná", "Shakira", "Enrique Iglesias", "Juanes", "Ricky Martin",
            "La Oreja de Van Gogh", "Héroes del Silencio", "Café Tacvba", "Julieta Venegas", "Soda Stereo",
            "Amaral", "Jarabe de Palo", "Los Fabulosos Cadillacs", "Mecano", "Juan Luis Guerra",
            "Gloria Estefan", "Carlos Vives", "Celia Cruz", "Marc Anthony", "Chayanne",
            "Alejandro Sanz", "Vicente Amigo", "Los Secretos", "Los Suaves", "Fito y Fitipaldis",
            "La Fuga", "Extremoduro", "Hombres G", "Jarabe de Palo", "Bunbury",
            "El Canto del Loco", "Estopa", "Macaco", "Miguel Bosé", "Nino Bravo",
            "Orishas", "Pastora Soler", "Rosario", "Sergio Dalma", "Camila",
            "Daddy Yankee", "RBD", "Reik", "Mana", "Jesse & Joy",
            "Mägo de Oz", "La Quinta Estación", "David Bisbal", "India Martínez", "Niña Pastori",
            "La Mala Rodríguez", "Jarabe de Palo", "Estopa", "Malú", "Melendi"
        )

        val fakePlayListName = listOf(
            TrackData("Amerika", "Rammstein", 226000, ""),
            TrackData("Reise, Reise", "Rammstein", 251000, ""),
            TrackData("Du Hast", "Rammstein", 234000, ""),
            TrackData("Tequila", "Korpiklaani", 162000, ""),
            TrackData("Eiskalter Engel", "LaFee", 233000, ""),
            TrackData("Straight to the Heart", "Battle Beast", 211000, ""),
            TrackData("Ich Bin Ich", "LaFee", 291000, ""),
            TrackData("Una mattina", "Ludovico Einaudi", 206000, ""),
            TrackData("Nur geträumt", "NENA", 220000, ""),
            TrackData("Irgendwie, irgendwo, irgendwann", "NENA", 435000, ""),
            TrackData("99 Luftballons", "NENA", 230000, ""),
            TrackData("Люби меня люби", "Гречка", 187000, ""),
            TrackData("Закрой за мной дверь, я ухожу", "КИНО", 256000, ""),
            TrackData("Commander Shepard", "Miracle of Sound", 208000, ""),
            TrackData("House of the Rising Sun", "Ramin Djawadi", 84000, ""),
            TrackData("New Zodiac", "Zodiac", 248000, ""),
            TrackData("Where", "Evgeny Grinko", 125000, ""),
            TrackData("Ask the Mountains", "Vangelis", 472000, ""),
            TrackData("Desert Traveller", "Karunesh, Ankita", 383000, ""),
            TrackData("Twilight Of The Thunder God", "Amon Amarth", 248000, ""),
            TrackData("Polly", "Nirvana", 173000, ""),
            TrackData("Косово Поле", "Кипелов", 368000, ""),
            TrackData("Sleepsong", "Secret Garden", 204000, ""),
            TrackData("Я сделан из такого вещества", "Василий К.", 175000, ""),
            TrackData("Исповедь тамплиера", "Fun Mode", 218000, ""),
            TrackData("I'm Shipping Up To Boston", "Dropkick Murphys", 154000, ""),
            TrackData("Another Blue Night", "Snowy White, The White Flames", 309000, ""),
            TrackData("How Was It for You", "Snowy White", 166000, ""),
            TrackData("La Vie En Rose", "Louis Armstrong and His Orchestra", 205000, ""),
            TrackData("Bonden og Kragen", "Myrkur", 153000, ""),
            TrackData("Три товарища", "Эдуард Артемьев", 129000, ""),
            TrackData("Si el poeta eres tú", "Soledad Bravo", 158000, ""),
            TrackData("Hasta siempre", "Soledad Bravo", 270000, ""),
            TrackData("Night Fit (Velvet Box)", "Thomas Newman", 91000, ""),
            TrackData("In The Air Tonight", "Phil Collins", 331000, ""),
            TrackData("Yesterday", "Pepito Ros, Sandro Gibellini Trio", 175000, ""),
            TrackData("Engel", "Gregorian", 307000, ""),
            TrackData("Barracuda", "Heart", 274000, ""),
            TrackData("Helvegen", "Kalandra", 412000, ""),
            TrackData("Wandering Spirits", "David Arkenstone", 397000, ""),
            TrackData("The Council Of Elrond", "Howard Shore, Enya", 229000, ""),
            TrackData("The Mandalorian", "Ludwig Goransson", 198000, ""),
            TrackData("Wicked Game", "Stone Sour", 267000, ""),
            TrackData("Make Rainbows", "Lazy Jazz Cat", 125000, ""),
            TrackData("Pali Się", "Tulia", 171000, ""),
            TrackData("Nothing Else Matters", "Tulia", 242000, ""),
            TrackData("Runnin' Wild", "Airbourne", 218000, ""),
            TrackData("All of My Life", "Phil Collins", 335000, ""),
            TrackData("Can't Turn Back the Years", "Phil Collins", 278000, ""),
            TrackData("Another Day in Paradise", "Phil Collins", 321000, ""),
            TrackData("True Sorry", "Ibrahim Maalouf", 291000, ""),
            TrackData("Three Comrades", "Вадим Эйленкриг, Игорь Бутман...", 268000, ""),
            TrackData("Loud and Heavy", "Cody Jinks", 439000, ""),
            TrackData("Awake", "Jeremy Soule", 92000, ""),
            TrackData("The Expanse Theme", "Clinton Shorter", 64000, ""),
            TrackData("Black", "Kari Kimmel", 231000, ""),
            TrackData("Must Be the Whiskey", "Cody Jinks", 237000, ""),
            TrackData("Держава", "Василий К.", 237000, ""),
            TrackData("Crazy Situation Blues", "Snowy White, The White Flames", 237000, ""),
            TrackData("Призрачный взвод", "Кипелов", 299000, ""),
            TrackData("Королева Банши", "Fun Mode", 258000, ""),
            TrackData("World Without End", "Gregorian", 257000, ""),
            TrackData("Nothing Else Matters", "Gregorian", 332000, ""),
            TrackData("My Immortal", "Gregorian", 326000, ""),
            TrackData("Losing My Religion", "Gregorian", 352000, ""),
            TrackData("One of Us", "Gregorian", 337000, ""),
            TrackData("Join Me", "Gregorian", 310000, ""),
            TrackData("Moment of Peace", "Gregorian", 238000, ""),
            TrackData("Kyrie Eleison", "Stellamara", 343000, ""),
            TrackData("Patience", "Countdown Studio Band", 201000, ""),
            TrackData("Unfaithful", "Sassydee", 228000, ""),
            TrackData("Halcyon Flowering Seas", "Deepspace", 144000, ""),
            TrackData("Хозяин леса", "Король и Шут", 188000, ""),
            TrackData("Sleepsong", "Secret Garden, Fionnuala Gill", 290000, ""),
            TrackData("Lotus", "Secret Garden", 275000, ""),
            TrackData("Icebergs", "Daria Shakhova", 206000, ""),
            TrackData("Prituri se planinata", "Stellamara", 260000, ""),
            TrackData("Herr Mannelig", "Gilead", 411000, ""),
            TrackData("Sleepsong", "David Arkenstone, David Davidson", 276000, ""),
            TrackData("Cocaine", "Nomy", 251000, ""),
            TrackData("For the Damaged Coda", "Blonde Redhead", 157000, ""),
            TrackData("In The End", "Tommee Profitt, Fleurie, Mellen Gi", 218000, ""),
            TrackData("Take Me To The River", "Kaleida", 201000, ""),
            TrackData("Long And Lonesome Road", "Shocking Blue", 171000, ""),
            TrackData("Ветер перемен", "Чичерина", 205000, ""),
            TrackData("Crawling Up a Hill", "Katie Melua", 202000, ""),
            TrackData("Paranoid", "Black Sabbath", 167000, ""),
            TrackData("Mississippi", "The Secret Sisters", 262000, ""),
            TrackData("Увядание листьев", "Хелависа", 253000, ""),
            TrackData("Крепче, воин, сжимай топор", "Сколот", 358000, ""),
            TrackData("Немного жаль", "Александр Иванов", 254000, ""),
            TrackData("Führe Mich", "Rammstein", 256000, ""),
            TrackData("Лесник", "Евгения Скачкова & Александра Кузнецова", 147000, ""),
            TrackData("Sail Away", "David Gray", 315000, ""),
            TrackData("Das Gefühl", "Annett Louisan", 165000, ""),
            TrackData("Звёздные капитаны", "Марко Поло", 314000, ""),
            TrackData("Мыловар", "Ольга Арефьева и Ковчег", 242000, ""),
            TrackData("Место для шага вперёд", "Карелия", 251000, ""),
            TrackData("When I'm Gone", "3 Doors Down", 248000, ""),
            TrackData("Kryptonite", "3 Doors Down", 235000, ""),
            TrackData("Piece by Piece", "Katie Melua", 201000, ""),
            TrackData("Удача и судьба", "BY Effect", 225000, ""),
            TrackData("Менестрели", "Марко Поло", 326000, ""),
            TrackData("Саванна", "Инкогнито", 174000, ""),
            TrackData("Кицунэ", "Мельница", 258000, ""),
            TrackData("Бледный бармен (Часть вселенной)", "Александр Иванов", 202000, ""),
            TrackData("Первый снег", "Моральный кодекс", 251000, ""),
            TrackData("Shelby Rd.", "Thomas Newman", 114000, ""),
            TrackData("Wonderful Life", "Katie Melua", 247000, ""),
            TrackData("Running In the Wind", "Paolo Vivaldi", 115000, ""),
            TrackData("Get Up", "Dorothy", 118000, ""),
            TrackData("Scarborough Fair", "YoGa", 158000, ""),
            TrackData("Memories from Colonia", "Paolo Vivaldi", 87000, ""),
            TrackData("Le Cœur Au Bout Des Doigts", "Jacqueline Taieb", 160000, ""),
            TrackData("Rio Grande", "Freedom Fry", 271000, ""),
            TrackData("Pearls in Her Hair", "Omega", 330000, ""),
            TrackData("Wanted Dead Or Alive", "Bon Jovi", 308000, ""),
            TrackData("Down by the River", "Rachel Hardy", 135000, ""),
            TrackData("Home", "Minniva, Orion's Reign", 171000, ""),
            TrackData("Kolybelnaya", "Natural Spirit", 338000, ""),
            TrackData("Oh Me", "Live Nirvana", 206000, ""),
            TrackData("The Only", "Static-X", 171000, ""),
            TrackData("Letter to Madeline", "Ian Noe", 269000, ""),
            TrackData("Sweet Child O' Mine", "Guns N' Roses", 355000, ""),
            TrackData("Смерти нет", "Тэм Гринхилл", 153000, ""),
            TrackData("Прощай", "Йовин", 257000, ""),
            TrackData("Там Лин", "Elenor", 131000, ""),
            TrackData("Condor", "Dust Follows", 188000, ""),
            TrackData("SunRise", "Northside", 199000, ""),
            TrackData("Forever Young", "Alphaville", 226000, ""),
            TrackData("Аваллон", "Elenor", 193000, ""),
            TrackData("Возьми моё сердце", "Ария", 0, ""),
            TrackData("Осколок льда", "Ария", 325000, ""),
            TrackData("P'tite pute", "Saez", 267000, ""),
            TrackData("Гвардия Петра", "Radio Tapok", 209000, ""),
            TrackData("Tango Por Una Cabeza", "Carlos Gardel", 281000, ""),
            TrackData("Greensleeves", "Lesfm", 110000, ""),
            TrackData("J'accuse", "Saez", 268000, ""),
            TrackData("Anything, Anything", "Dark Nights: Death Metal Grey Daze", 192000, ""),
            TrackData("Capsize", "How Nice", 241000, ""),
            TrackData("Roads", "Rose Of The West", 265000, ""),
            TrackData("Dance With Me", "Nouvelle Vague, Mélanie Pain", 220000, ""),
            TrackData("Wet Dream", "Wet Leg", 140000, ""),
            TrackData("Рыцарь и королева", "Fun Mode", 239000, ""),
            TrackData("Ain't No Sunshine", "New York Jazz Lounge", 161000, ""),
            TrackData("When a Man Loves a Woman", "New York Jazz Lounge", 247000, ""),
            TrackData("Out There", "Carlo Ambrosio, Mario Buonamassa", 393000, ""),
            TrackData("Desert of the Mind", "Setsuna", 307000, ""),
            TrackData("Ready For The Storm", "Deanta", 219000, ""),
            TrackData("Mindfields", "Distortion Flames", 255000, ""),
            TrackData("Gold Guns Girls", "Metric", 247000, ""),
            TrackData("Ballad of Serenity", "Sonny Rhodes", 210000, ""),
            TrackData("The Line Live", "Juzzie Smith", 200000, ""),
            TrackData("Naturalness", "Vasily Dvortsov", 165000, ""),
            TrackData("Giant", "Osi and the Jupiter", 312000, ""),
            TrackData("Метаморфоза", "лунный бард", 200000, ""),
            TrackData("K.B.A.G.", "Jennifer Rostock", 181000, ""),
            TrackData("ЧеловекаПечаль", "KANATAMI", 243000, ""),
            TrackData("Fred Bear", "Ted Nugent", 462000, ""),
            TrackData("Feathers And Down", "The Cardigans", 270000, ""),
            TrackData("You Know", "8mm", 221000, ""),
            TrackData("Волонтёр", "BooTabs", 119000, ""),
            TrackData("El Labba", "Ÿuma", 233000, ""),
            TrackData("Different Stars", "Trespassers William", 283000, ""),
            TrackData("Water and Wine", "Acoustic Aleah", 289000, ""),
            TrackData("Sirens Call Shaka Ponk Remix", "Cats On Trees, Shaka Ponk", 227000, ""),
            TrackData("Shape of My Heart", "Jody Gwin", 276000, ""),
            TrackData("Feeling Good", "Nina Simone", 175000, ""),
            TrackData("Eyes On Fire", "Blue Foundation", 302000, ""),
            TrackData("Свет былой любви", "Ария", 258000, ""),
            TrackData("Nothing Else Matters", "Apocalyptica", 285000, ""),
            TrackData("Rape Me Solo Acoustic", "Nirvana", 201000, ""),
            TrackData("Last Night", "Joy Santec Music Orchestra", 203000, ""),
            TrackData("Epic China", "Jonas West", 168000, ""),
            TrackData("Too Much Money", "Automatic", 136000, ""),
            TrackData("Sans toi", "Pomme", 242000, ""),
            TrackData("Dream On", "Cinematic Pop, Cosette", 188000, ""),
            TrackData("Draw Your Weapon", "Philter", 188000, ""),
            TrackData("Kidnapping An Heiress", "Black Box Recorder", 166000, ""),
            TrackData("Je t'aime comme je t'aime", "Maëlle", 161000, ""),
            TrackData("Memento", "Omega One", 229000, ""),
            TrackData("Go Walking Down There", "Chris Isaak", 170000, ""),
            TrackData("Right Time", "Norman", 112000, ""),
            TrackData("Planet of the Dreamers", "Jacuzzi Boys", 120000, ""),
            TrackData("Холодное тело", "Король и Шут", 160000, ""),
            TrackData("Le Point Zéro", "Freedom Fry", 251000, ""),
            TrackData("Signs", "Ikon", 252000, ""),
            TrackData("All Souls Night 2004 Remaster HD [Remastered]", "Loreena McKennitt", 308000, ""),
            TrackData("Paranoid (Буря мглою небо кроет, Cover)", "Bagira", 168000, ""),
            TrackData("Вечный пламень", "Таверна", 123000, ""),
            TrackData("Auf halber Strecke", "Elif", 261000, ""),
            TrackData("Very Ape", "Nirvana", 114000, ""),
            TrackData("Now", "Staind", 224000, ""),
            TrackData("Cry Sister Radio Edit", "Royal Bliss", 189000, ""),
            TrackData("The Trooper", "Lemmy Kilmister, Phil Campbell, Chris Slade, Chuck Wright, Rocky George", 246000, ""),
            TrackData("Eight Days", "Slowly Rolling Camera", 353000, ""),
            TrackData("Hijo de la Luna", "Hija de la Luna", 263000, ""),
            TrackData("Was wollen wir trinken Bonustrack", "Geyers", 310000, ""),
            TrackData("Engel weinen", "Herren", 246000, ""),
            TrackData("La Casa del Sol Naciente", "Frida Boccara", 173000, ""),
            TrackData("Пора возвращаться домой", "Би-2, Oxxxymiron", 288000, ""),
            TrackData("Patagonia", "José Larralde", 255000, ""),
            TrackData("Rodrigo: En Aranjuez con tu amor", "Andrea Bocelli, London Symphony Orchestra, Lorin Maazel", 206000, ""),
            TrackData("Súbele el volumen", "Danay Suárez", 229000, ""),
            TrackData("The Call of the Mountains", "Eluveitie, Masha Scream", 254000, ""),
            TrackData("Самурай", "Марко Поло", 176000, ""),
            TrackData("Морская", "Дом Ветров", 170000, ""),
            TrackData("Le long de l'eau", "Cécile Corbel", 200000, ""),
            TrackData("Louis", "Barbara Pravi", 207000, ""),
            TrackData("Pilule", "Saez", 318000, ""),
            TrackData("Рождённые жить", "JT.Soul", 340000, ""),
            TrackData("Ev Sistr", "Nasty Anksi", 267000, ""),
            TrackData("Fukurou Russian Version", "Sati Akura", 290000, ""),
            TrackData("Вечно молодой (симфония брат)", "CAGMO", 230000, ""),
            TrackData("Back in Black", "Jennel Garcia", 178000, ""),
            TrackData("Bad Boys Running Wild", "Scorpions", 236000, ""),
            TrackData("Black", "Anthony Graham", 139000, ""),
            TrackData("Не для меня...", "Кипелов", 189000, ""),
            TrackData("L'amore è un'altra cosa", "Arisa", 223000, ""),
            TrackData("Six Blade Knife", "Dire Straits", 252000, ""),
            TrackData("Hell Has No Mercy", "The 69 Eyes", 403000, ""),
            TrackData("Zerstören was wir lieben", "Mantus", 246000, ""),
            TrackData("Re-Align", "Godsmack", 260000, ""),
            TrackData("I Wanna Be Your Dog 2005 Remaster", "The Stooges", 190000, ""),
            TrackData("Liar, Liar", "The Castaways", 115000, ""),
            TrackData("Think Twice Before You Go", "John Lee Hooker", 124000, ""),
            TrackData("Another Brick in the Wall Smooth Jazz All Stars", "Smooth Jazz All Stars", 258000, ""),
            TrackData("Flight of the Incubus", "Bebopovsky And The Orkestry Podyezdov", 272000, ""),
            TrackData("Dougné te soyé", "Amadou & Mariam", 253000, ""),
            TrackData("Sanza", "Kanaka", 169000, ""),
            TrackData("Морская болезнь", "Мумий Тролль", 281000, ""),
            TrackData("Чувства", "Animal ДжаZ", 225000, ""),
            TrackData("The Unforgiven", "Ha*Ash", 245000, ""),
            TrackData("Teardrop", "Eklipse", 257000, ""),
            TrackData("Happy Man triple j Like A Version", "Laurel", 203000, ""),
            TrackData("Кроссворд", "Проще сложного", 190000, ""),
            TrackData("Свобода", "Проще сложного", 167000, ""),
            TrackData("Ноты", "Проще сложного", 238000, ""),
            TrackData("КАД", "Проще сложного", 195000, ""),
            TrackData("Just Do It", "Проще сложного", 208000, "")
        )
    }
}